### ISSUE TITLE
Workflow advancement calculator

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#13]
The AdvancementCalculator calculates the sequence of activation of Activities in a workflow. Currently, this misbehaves under certain conditions. It is also very complex in its current form.

**Comment by abranson** [comment]
Should be helped by #1

**Comment by kovax** [comment]
AdvancamentCalculator is only used in Join to calculate if there is any active vertex 'before' the Join. If there is none, it will trigger (run) its single outgoing edge. The whole calculation is done by the parent CompositeAct scanning of it layout and its children's layout from start to end.

I propose the following:
- reimplement AdvancmentCalculator for Join only
- use algorithm which follows the incoming edges until it finds an active Activity (CA or EA) or it visited all Vertexes of the current CA
- there is no need to check child CompositeActs, because CA finishes automatically 
- there is no need to check the incoming edge which called the runNext() of the Join

**Comment by abranson** [comment]
Sounds good, but is that simpler than the current implementation?
What do you think, @ogattaz ?

**Comment by kovax** [comment]
It should be simpler as it will not visit composite acts recursively, but it will not be simple algorithm.

Is it possible to identify if such problem can be translated to a graph traversal/query algorithm?

**Comment by abranson** [comment]
I think there's an attempt to do that already in there. There's lots of traversal and tagging stuff in the graph lib.

**Comment by kovax** [comment]
I just had a quick look on GraphTraversal in kernel. Shall I give it a try?

**Comment by abranson** [comment]
Yes, I'd speak to @ogattaz about it too, because he has the most experience with hacking that about. He may have prior experience of trying to use the traversal in it.

**Comment by abranson** [comment]
0dc70d2d2e97f3dc6fe74e1a4db0b9b0de32f176 attempts to replace the AdvancementManager with a three line use of the GraphTraversal util

**Comment by abranson** [comment]
Going to close this - seems to work.
