### ISSUE TITLE
SVG rendering of the lifecycle of an item

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#167]
The goal is to deliver an SVG representation the lifecycle state in the response to a rest request according the accept header.

The implementation could be based on the svg renderer Apache Batik as the Umlet project.

**Comment by kovax** [comment]
PlantUML uses Graphiz, which could generate JPG and SVG as well

http://plantuml.com/graphviz-dot

**Comment by kovax** [comment]
We could also use jfreesvg:

http://www.jfree.org/jfreesvg/

This is the performance comparison of Batic and JFreeSVG

http://www.object-refinery.com/blog/blog-20140423.html

**Comment by ogattaz** [comment]
Yes, jfreesvg seems to be more efficient than Batik.
Batik isn't my choice, it's only the library you told us as the one used in Umlet.
So yes for jfreesvg.

**Comment by kovax** [comment]
@ogattaz, jfreesvg has GPLv3 licence, which might prohibit its use.

**Comment by kovax** [comment]
#166

**Comment by kovax** [comment]
SVG rendering will not be supported by the kernel only binary image (#166), because it requires an external library. The implemented renderers are based on Graphics2D which can be used by external libraries like jfreesvg to create the SVG version of the picture. Check test class LifecycleRendererTest.
