### ISSUE TITLE
Add a "bootstrapper" listener

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#43]
Goal : To be alerted when the bootstrapper thread is done.

Proposal : Give a IBootstrapListener instance to the kernel as we can give it today a LDAPAuthManager or a LDAPLookupManager instance using the Cristalise properties map.  

``` java
/**
 * @author Cristal-ise team - Copyright 2015
 *
 */
public interface IBootstrapListener {
	/**
	 * Called when the bootstrap thread starts
	 */
	void beginBootstrap();
	/**
	 * Called when the bootstrap thread ends 
	 */
	void endBootstrap();
	/**
	 * Called when an Exception is thrown during the bootstrap thread running
	 */
	void onError();
}
```

**Comment by abranson** [comment]
I've recently talked about Bootstrap event monitoring with Zsolt, and the current favourite is to include a Bootstrap activity in the Server Item's lifecycle, which should become more of a representation of the server process lifecycle. This workflow would be reinitialized every time the server starts, and the Bootstrap activity started and stopped with the bootstrap thread. Interested processes could check the state of that workflow, or subscribe to events in the server in order to see what's going on. We could add additional activities in the future.

I'm generally not very keen on adding interfaces if we can avoid it, as I don't like adding arbitrary things to the kernel that steepen the learning curve. The kernel should be getting simpler over time.

**Comment by ogattaz** [comment]
Your proposal is great, but we have a modularization problem to solve : 

how can a module knows that the bootstrap is done ?

**Comment by abranson** [comment]
The module xsd defines four 'events' on which to call scripts: startup, shutdown, install and uninstall. The 'startup' event runs per module, after its Items are registered. Is this useful? Otherwise we could introduce another event to run after the bootstrap has finished.

Of the others, shutdown scripts are run at the beginning of Gateway.close(), but install and uninstall aren't implemented yet.

**Comment by abranson** [comment]
I went for 'initialized'

**Comment by ogattaz** [comment]
could-you explain the way you choose ? I'm not sure

**Comment by abranson** [comment]
You can now set a script in a module to run when the bootstrap thread is finished.
