### ISSUE TITLE
Item with the same name but with different path.

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#45]
It's is possible to have 2 outcomedesc items of the same type and the same name but with different path.

![bug 45](https://cloud.githubusercontent.com/assets/9263650/9324620/700f47da-458c-11e5-90dd-08a74f082c55.JPG)

But then you cannot use them, i.e. referencing them (put the schema Name in SchemaType) in an Activity, because when running the activity it's say there is too many Item for this reference.
```
EXCEPTION:org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  Too many matches for PropertyDescription in /desc/OutcomeDesc/
```
If you try to put the path (ex /agilium/process-instance/PropertyDescription) instead, it doesn't work either : cannot find the item.
```
EXCEPTION:org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  No match for agilium/process-instance/PropertyDescription in /desc/OutcomeDesc/
```
I assume it's the same with other Item (script, activity, workflow ...).

**Comment by abranson** [comment]
This should cease to be a problem after #4 is complete, as this should remove the dependency on fixed root description contexts. After this, descriptions and definitions should reference each other through collections, and activity instances will hold the UUIDs of their definitions instead of naming them.
