### ISSUE TITLE
Cannot stop and relaunch the full Cristal kernel server in the same VM

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#67]
There are functional test cases which needs to initialise a fully functional cristal kerner server in the same VM, but those test will fail because the TCP/IP port of CORBA is not released after Gateway.close() has returned.

**Comment by abranson** [comment]
Either we're not shutting down the POA and ORB properly, or there's a bug in the Sun CORBA implementation, because the acceptors in the CorbaTransportManager never get closed during ORB destroy.
This bit of code will force them to close, but can't really go in the kernel because it uses a restricted API and is hacky as hell. However, it does let your tests work properly:

```java
            com.sun.corba.se.spi.transport.CorbaTransportManager mgr = ((com.sun.corba.se.impl.orb.ORBImpl)Gateway.getORB()).getCorbaTransportManager();
            for (Object accept: mgr.getAcceptors()) {
            	((com.sun.corba.se.pept.transport.Acceptor) accept).close();
            }
```

If we can't find out how to do this properly, and I continue to have no luck finding how to switch the IIOP to use SSL, then we will consider whether to switch ORB. JacORB might be a well-supported, drop-in replacement that might not have these problems. It's a bit late in this phase to be adding new dependencies to the kernel though.

**Comment by abranson** [comment]
We've worked around this in the testing. It's still a problem, but will require a CORBA switch to resolve. Closing for now.
